"""
双目视觉闭环抓取控制器
========================
基于机械手末端双目摄像头，实时测量苹果距离和方位，
使用混合策略控制机械臂完成抓取：
  1. 预计算 waypoints 粗略接近
  2. 双目三角测量精确定位（中等距离最有效）
  3. MuJoCo 数值 IK 微调
  4. 夹爪闭合 + 提起

Usage:
    python src/stereo_pick_controller.py
    python src/stereo_pick_controller.py --no-viewer
    python src/stereo_pick_controller.py --save-frames
"""

import argparse
import math
import time

import numpy as np

import mujoco
import mujoco.viewer

from stereo_vision import StereoCameraSystem, StereoVisionProcessor
from mujoco_ik import compute_ik_mujoco

SCENE_XML = "src/robot_scene.xml"

# Pre-computed waypoints (verified in MuJoCo, generated by numerical IK)
WAYPOINTS = [
    np.array([0.0, 0.5, -1.2, 0.0, 0.8, 0.0]),       # 0: home
    np.array([0.0, 0.5292, -0.6397, 0.0, 0.9542, 0.0]),  # 1
    np.array([0.0, 0.5584, -0.0794, 0.0, 1.1083, 0.0]),  # 2
    np.array([0.0, 0.5876, 0.481, 0.0, 1.2625, 0.0]),    # 3: near apple, stereo works
    np.array([0.0, 0.6168, 1.0413, 0.0, 1.4166, 0.0]),   # 4: very close, stereo very accurate
    np.array([0.0, 0.6459, 1.6016, 0.0, 1.5708, 0.0]),   # 5: grasp position
]

# Gripper
GRIPPER_OPEN = 0.035
GRIPPER_CLOSED = 0.005

# Control parameters
STEP_DT = 0.05
MAX_DELTA_Q = 0.08
APPROACH_OFFSET = np.array([0.0, 0.0, 0.08])
GRASP_DIST_THRESH = 0.06

# Vision trust thresholds
MAX_RAY_DIST = 0.02       # triangulation is trustworthy when rays are this close
MAX_POS_DEVIATION = 0.15  # reject visual estimate if >15cm from expected apple pos


def lerp_array(a, b, t):
    return a + t * (b - a)


class StereoRobotEnv:
    """MuJoCo environment with stereo cameras and kinematic control."""

    def __init__(self):
        self.model = mujoco.MjModel.from_xml_path(SCENE_XML)
        self.data = mujoco.MjData(self.model)
        self.cam = StereoCameraSystem(self.model, self.data)
        self.vision = StereoVisionProcessor(self.model, self.data)

        # Joint qpos addresses
        self.qpos_adr = []
        for i in range(6):
            jnt_id = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_JOINT, f"joint{i + 1}")
            self.qpos_adr.append(self.model.jnt_qposadr[jnt_id])
        self.grip_adr = []
        for name in ["left_gripper_joint", "right_gripper_joint"]:
            jnt_id = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_JOINT, name)
            self.grip_adr.append(self.model.jnt_qposadr[jnt_id])

        self.apple_body_id = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_BODY, "apple")
        self.gripper_body_id = mujoco.mj_name2id(self.model, mujoco.mjtObj.mjOBJ_BODY, "gripper")

        # State
        self.joint_angles = np.copy(WAYPOINTS[0])
        self.gripper_opening = GRIPPER_OPEN
        self.phase = "approach"
        self.grasped = False
        self.apple_attached = False
        self._apply_joints()

        # Apple position estimate from vision
        self.apple_estimate = None
        self.estimation_method = None

    def _apply_joints(self):
        for i in range(6):
            self.data.qpos[self.qpos_adr[i]] = self.joint_angles[i]
        self.data.qpos[self.grip_adr[0]] = self.gripper_opening
        self.data.qpos[self.grip_adr[1]] = self.gripper_opening
        if self.apple_attached:
            ee = self.data.xpos[self.gripper_body_id].copy()
            self.model.body("apple").pos = ee + np.array([0, 0, -0.06])
        mujoco.mj_forward(self.model, self.data)

    def get_end_effector_pos(self):
        return self.data.xpos[self.gripper_body_id].copy()

    def get_gripper_xmat(self):
        return self.data.xmat[self.gripper_body_id].copy().reshape(3, 3)

    def get_apple_pos(self):
        return self.data.xpos[self.apple_body_id].copy()

    def set_joints(self, q, gripper):
        self.joint_angles = np.copy(q)
        self.gripper_opening = gripper
        self._apply_joints()

    def attach_apple(self):
        if not self.apple_attached:
            self.apple_attached = True
            self._apply_joints()

    def step(self):
        if self.apple_attached:
            self._apply_joints()

    def close(self):
        self.cam.close()

    def update_apple_estimate(self, stereo_frames):
        """
        Update apple position using stereo vision.
        Returns (position, method) or (None, reason).
        """
        ee_pos = self.get_end_effector_pos()
        expected_apple = np.array([0.35, 0.0, 0.0775])

        # 1. Try triangulation (most accurate when both cameras see the apple)
        tri_result, left_det, right_det = self.vision.estimate_apple_position_triangulation(stereo_frames)

        if tri_result is not None:
            pos = tri_result["position"]
            ray_dist = tri_result["ray_distance"]
            dist_from_expected = np.linalg.norm(pos - expected_apple)

            # Validation: rays should nearly intersect, and result should be near expected apple position
            if ray_dist < MAX_RAY_DIST and dist_from_expected < MAX_POS_DEVIATION:
                # Also check that intersection is in front of both cameras
                c1, r1 = self.vision.pixel_to_world_ray("left_camera", *left_det["center"])
                c2, r2 = self.vision.pixel_to_world_ray("right_camera", *right_det["center"])
                w0 = c1 - c2
                a = np.dot(r1, r1)
                b = np.dot(r1, r2)
                c = np.dot(r2, r2)
                d = np.dot(r1, w0)
                e = np.dot(r2, w0)
                denom = a * c - b * b
                if abs(denom) > 1e-10:
                    t1 = (b * e - c * d) / denom
                    t2 = (a * e - b * d) / denom
                    if t1 > 0 and t2 > 0:
                        self.apple_estimate = pos
                        self.estimation_method = "triangulation"
                        return pos, "triangulation"

        # 2. Fallback: single-camera detection + ground-plane intersection
        # Use whichever camera has the stronger detection
        best_det = None
        best_cam = None
        for cam_name, det in [("left_camera", left_det), ("right_camera", right_det)]:
            if det is not None and det["max_score"] > 100:
                if best_det is None or det["max_score"] > best_det["max_score"]:
                    best_det = det
                    best_cam = cam_name

        if best_det is not None:
            origin, direction = self.vision.pixel_to_world_ray(best_cam, *best_det["center"])
            if abs(direction[2]) > 1e-6:
                t = (0.0775 - origin[2]) / direction[2]
                if t > 0:
                    pos = origin + t * direction
                    dist_from_expected = np.linalg.norm(pos - expected_apple)
                    if dist_from_expected < MAX_POS_DEVIATION:
                        self.apple_estimate = pos
                        self.estimation_method = f"single_{best_cam}"
                        return pos, f"single_{best_cam}"

        # 3. Point cloud fallback (slower but can work with partial detections)
        pc_result = self.vision.estimate_apple_from_pointcloud(stereo_frames)
        if pc_result is not None:
            pos = pc_result["position"]
            dist_from_expected = np.linalg.norm(pos - expected_apple)
            if dist_from_expected < MAX_POS_DEVIATION and pc_result["point_count"] > 20:
                self.apple_estimate = pos
                self.estimation_method = "pointcloud"
                return pos, "pointcloud"

        self.apple_estimate = None
        self.estimation_method = "none"
        return None, "none"


class StereoGraspController:
    """
    Hybrid grasp controller:
      - Open-loop waypoints for coarse approach (phases 0-3)
      - Stereo vision + MuJoCo IK for fine positioning (phases 4-5)
      - Grasp and lift
    """

    def __init__(self, env):
        self.env = env
        self.phase = "approach"
        self.waypoint_idx = 0
        self.target_q = np.copy(WAYPOINTS[0])
        self.step_count = 0
        self.vision_refined_target = None  # apple position refined by stereo vision

    def move_toward_q(self, q_target, speed=0.5):
        """Move joint angles toward target with limited step size."""
        delta = q_target - self.env.joint_angles
        delta = np.clip(delta, -MAX_DELTA_Q, MAX_DELTA_Q)
        new_q = self.env.joint_angles + delta * speed
        # Clamp
        for i in range(6):
            lo, hi = (-math.pi, math.pi) if i in [0, 3, 5] else (-math.pi / 2, math.pi / 2)
            if i == 2:
                lo, hi = (-2.0, 2.0)
            new_q[i] = float(np.clip(new_q[i], lo, hi))
        return new_q

    def transition(self, new_phase):
        print(f"  -> Phase: {new_phase.upper()}")
        self.phase = new_phase

    def run_step(self, stereo_frames):
        """Execute one control step. Returns True if task is done."""
        self.step_count += 1
        ee_pos = self.env.get_end_effector_pos()

        # === Update apple position from stereo vision ===
        est_pos, est_method = self.env.update_apple_estimate(stereo_frames)
        if est_pos is not None:
            self.vision_refined_target = est_pos
            dist = np.linalg.norm(est_pos - ee_pos)
            print(f"  [Vision:{est_method:15s}] Apple at [{est_pos[0]:.3f}, {est_pos[1]:.3f}, {est_pos[2]:.3f}], "
                  f"dist={dist:.3f}m")

        # === Phase machine ===
        if self.phase == "approach":
            return self._phase_approach()
        elif self.phase == "vision_refine":
            return self._phase_vision_refine(est_pos, ee_pos)
        elif self.phase == "descend":
            return self._phase_descend(est_pos, ee_pos)
        elif self.phase == "grasp":
            return self._phase_grasp()
        elif self.phase == "lift":
            return self._phase_lift()
        elif self.phase == "done":
            return True

        return False

    def _phase_approach(self):
        """Follow open-loop waypoints until near apple."""
        # Check if we should advance to next waypoint
        err = np.linalg.norm(WAYPOINTS[self.waypoint_idx] - self.env.joint_angles)
        if err < 0.06 and self.waypoint_idx < len(WAYPOINTS) - 1:
            self.waypoint_idx += 1
            print(f"  -> Waypoint {self.waypoint_idx}/{len(WAYPOINTS) - 1}")

        self.target_q = WAYPOINTS[self.waypoint_idx]
        new_q = self.move_toward_q(self.target_q, speed=0.5)
        self.env.set_joints(new_q, GRIPPER_OPEN)

        # When reaching waypoint 3, check if stereo vision is working
        if self.waypoint_idx >= 3 and self.vision_refined_target is not None:
            dist = np.linalg.norm(self.vision_refined_target - self.env.get_end_effector_pos())
            if dist < 0.25:
                self.transition("vision_refine")

        # Fallback: if we've reached the last waypoint without vision, proceed anyway
        if self.waypoint_idx >= len(WAYPOINTS) - 1 and err < 0.05:
            self.transition("descend")

        return False

    def _phase_vision_refine(self, est_pos, ee_pos):
        """Use stereo vision + MuJoCo IK to precisely position above apple."""
        if est_pos is not None:
            approach_pos = est_pos + APPROACH_OFFSET
            # Use MuJoCo IK for precise positioning
            q_target = compute_ik_mujoco(
                self.env.model, self.env.data, self.env.gripper_body_id,
                approach_pos, self.env.qpos_adr, q0=self.env.joint_angles
            )
            self.target_q = q_target

        new_q = self.move_toward_q(self.target_q, speed=0.5)
        self.env.set_joints(new_q, GRIPPER_OPEN)

        err = np.linalg.norm(self.target_q - self.env.joint_angles)
        if err < 0.05:
            dist_to_apple = np.linalg.norm(self.env.get_end_effector_pos() - self.env.get_apple_pos())
            if dist_to_apple < 0.15:
                self.transition("descend")
            else:
                # Vision may have given a bad estimate; fall back to waypoint
                self.waypoint_idx = min(self.waypoint_idx + 1, len(WAYPOINTS) - 1)
                self.transition("approach")

        return False

    def _phase_descend(self, est_pos, ee_pos):
        """Move down to grasp position."""
        target_pos = None
        if est_pos is not None:
            target_pos = est_pos + np.array([0.0, 0.0, -0.01])  # slightly below center
        else:
            target_pos = np.array([0.35, 0.0, 0.0775])  # fallback to known apple position

        q_target = compute_ik_mujoco(
            self.env.model, self.env.data, self.env.gripper_body_id,
            target_pos, self.env.qpos_adr, q0=self.env.joint_angles
        )
        self.target_q = q_target

        new_q = self.move_toward_q(self.target_q, speed=0.5)
        self.env.set_joints(new_q, GRIPPER_OPEN)

        dist_to_apple = np.linalg.norm(self.env.get_end_effector_pos() - self.env.get_apple_pos())
        if dist_to_apple < GRASP_DIST_THRESH:
            self.transition("grasp")

        return False

    def _phase_grasp(self):
        """Close gripper and attach apple."""
        self.env.gripper_opening = GRIPPER_CLOSED
        self.env.set_joints(self.env.joint_angles, GRIPPER_CLOSED)
        self.env.grasped = True
        self.env.attach_apple()
        self.transition("lift")
        return False

    def _phase_lift(self):
        """Lift apple up."""
        lift_pos = np.array([0.35, 0.0, 0.25])
        if self.vision_refined_target is not None:
            lift_pos = self.vision_refined_target + np.array([0.0, 0.0, 0.15])

        q_target = compute_ik_mujoco(
            self.env.model, self.env.data, self.env.gripper_body_id,
            lift_pos, self.env.qpos_adr, q0=self.env.joint_angles
        )
        self.target_q = q_target

        new_q = self.move_toward_q(self.target_q, speed=0.4)
        self.env.set_joints(new_q, GRIPPER_CLOSED)

        err = np.linalg.norm(self.target_q - self.env.joint_angles)
        if err < 0.05:
            self.transition("done")

        return False


def control_step(env, controller, args):
    """Single control cycle: capture -> perceive -> act."""
    stereo_frames = env.cam.capture_stereo(save=args.save_frames)
    done = controller.run_step(stereo_frames)

    # Print stereo observation periodically
    if controller.step_count % 15 == 0:
        ee_pos = env.get_end_effector_pos()
        ee_xmat = env.get_gripper_xmat()
        obs = env.vision.format_observation(stereo_frames, ee_pos, ee_xmat)
        print(obs)

    return done


def run_headless(env, controller, args):
    step_idx = 0
    max_steps = args.max_steps

    while step_idx < max_steps and not env.grasped:
        t0 = time.time()
        done = control_step(env, controller, args)
        env.step()
        _sleep_remain(t0, STEP_DT)
        step_idx += 1
        if done:
            break

    print(f"\nFinished: {step_idx} steps, phase={controller.phase}")


def run_with_viewer(env, controller, args):
    with mujoco.viewer.launch_passive(env.model, env.data) as viewer:
        viewer.cam.azimuth = 135
        viewer.cam.elevation = -20
        viewer.cam.distance = 1.2
        viewer.cam.lookat[:] = [0.25, 0, 0.25]

        step_idx = 0
        max_steps = args.max_steps

        while viewer.is_running() and step_idx < max_steps and not env.grasped:
            t0 = time.time()
            done = control_step(env, controller, args)
            env.step()
            viewer.sync()
            _sleep_remain(t0, STEP_DT)
            step_idx += 1
            if done:
                break

    print(f"\nFinished: {step_idx} steps, phase={controller.phase}")


def _sleep_remain(t0, target_dt):
    elapsed = time.time() - t0
    sleep = target_dt - elapsed
    if sleep > 0:
        time.sleep(sleep)


def main():
    parser = argparse.ArgumentParser(description="Stereo vision closed-loop grasp controller")
    parser.add_argument("--no-viewer", action="store_true", help="Run without MuJoCo viewer")
    parser.add_argument("--save-frames", action="store_true", help="Save camera frames")
    parser.add_argument("--max-steps", type=int, default=400, help="Maximum control steps")
    args = parser.parse_args()

    print("=" * 60)
    print("双目视觉闭环抓取控制器")
    print("=" * 60)
    print(f"Viewer: {'OFF' if args.no_viewer else 'ON'} | Save frames: {'ON' if args.save_frames else 'OFF'}")
    print(f"Max steps: {args.max_steps}")
    print("=" * 60)

    env = StereoRobotEnv()
    controller = StereoGraspController(env)

    try:
        if args.no_viewer:
            run_headless(env, controller, args)
        else:
            run_with_viewer(env, controller, args)
    finally:
        env.close()

    print("\nDone.")


if __name__ == "__main__":
    main()
